--- Code generator: walks the AST and emits Lua 5.0 source text.

local emit_stmt = require("backend.lua50.stmt")
local const     = require("const")

--- Banner comment emitted at the top of a generated file. Static (no
--- timestamp) so output stays reproducible across builds.
local HEADER = table.concat({
    "--------------------------------------------------------------------",
    "-- Generated by the Lazarus compiler (v" .. const.compiler_version .. ")",
    "-- Target runtime: Lua 5.0",
    "-- This file is auto-generated. Do not edit by hand.",
    "--------------------------------------------------------------------",
}, "\n")

---@class CodegenOptions
---@field header? boolean  Emit the banner comment (default: true)
---@field entry?  boolean  Append the `main()` call when a `main` function exists (default: true)

---@class Codegen
---@field ast AST
local Codegen = {}
Codegen.__index = Codegen

---@param ast AST
---@return Codegen
function Codegen.new(ast)
    return setmetatable({ ast = ast }, Codegen)
end

--- True when a top-level function named `main` is declared — the program entry
--- point that the footer calls.
---@return boolean
function Codegen:_has_entry()
    for _, stmt in ipairs(self.ast.body) do
        if stmt.type == "FunctionDecl" and stmt.name == "main" then
            return true
        end
    end
    return false
end

--- Emit the program as a Lua 5.0 source string.
---
--- Layout: `HEADER` banner, a blank line, the translated statements, and — when
--- a `main` function is present — a trailing `main()` call. Each section is
--- toggleable via `opts`; disabling both yields the bare statement body (used by
--- the unit tests that assert on exact fragments).
---@param opts? CodegenOptions
---@return string
function Codegen:generate(opts)
    opts = opts or {}
    local with_header = opts.header ~= false
    local with_entry  = opts.entry  ~= false

    local body = {}
    for _, stmt in ipairs(self.ast.body) do
        body[#body + 1] = emit_stmt(stmt)
    end

    local sections = {}
    if with_header then
        sections[#sections + 1] = HEADER
    end
    if #body > 0 then
        sections[#sections + 1] = table.concat(body, "\n")
    end
    if with_entry and self:_has_entry() then
        sections[#sections + 1] = "main()"
    end

    return table.concat(sections, "\n\n")
end

return Codegen
