--- Code generator: walks the AST and emits Lua 5.0 source text.
---
--- A file is a **class**: the program lowers to a plain class table `C` whose
--- top-level functions and bindings are members. No metatables are used
--- (`__index` lookups are avoided for speed) — members are accessed by direct
--- indexing (`C.field`, `C.f(...)`). The emitted chunk is `local C = {}`, the
--- members, then (for a program) `return C.new(...)`: the **constructor is the
--- entry point**, so the chunk constructs the class (forwarding the launch
--- arguments `...`) and returns the instance. An entry program must define a
--- constructor.

local stmt = require("backend.lua50.stmt")
local Context = require("backend.lua50.context")
local const = require("const")
local Error = require("error")

local emit_member = stmt.emit_member

--- Banner comment emitted at the top of a generated file. Static (no
--- timestamp) so output stays reproducible across builds.
local HEADER = table.concat({
    "--------------------------------------------------------------------",
    "-- Generated by the Lazarus compiler (v" .. const.compiler_version .. ")",
    "-- Target runtime: Lua 5.0",
    "-- This file is auto-generated. Do not edit by hand.",
    "--------------------------------------------------------------------",
}, "\n")

---@class CodegenOptions
---@field header? boolean  Emit the banner comment (default: true)
---@field entry?  boolean  Append the `return C.new(...)` entry footer (default: true)

---@class Codegen
---@field ast        AST
---@field class_name string
local Codegen = {}
Codegen.__index = Codegen

--- @param ast         AST
--- @param class_name? string  The class name (defaults to "Main"); the CLI derives it from the filename.
---@return Codegen
function Codegen.new(ast, class_name)
    return setmetatable({ ast = ast, class_name = class_name or "Main" }, Codegen)
end

--- True when the class declares a constructor — the program entry point.
---@return boolean
function Codegen:_has_constructor()
    for _, stmt_node in ipairs(self.ast.body) do
        if stmt_node.type == "ConstructorDecl" then return true end
    end
    return false
end

--- Emit the program as a Lua 5.0 source string.
---
--- Layout: `HEADER` banner, the class table and its members, and — for a
--- program (`entry`) — `return C.new(...)` (the constructor entry point). Each
--- non-class section is toggleable via `opts`; disabling both yields just the
--- class table and members (used by unit tests that assert on member fragments).
---@param opts? CodegenOptions
---@return string
function Codegen:generate(opts)
    opts = opts or {}
    local with_header = opts.header ~= false
    local with_entry = opts.entry ~= false
    local class_name = self.class_name

    -- Classify the top-level declarations:
    --   • methods and `static` bindings are **members** (qualified `C.name`);
    --     the instance-method subset drives `obj.m(...)` → `C.m(obj, ...)`.
    --   • a non-static visibility binding is an **instance property**: it lives on
    --     the instance (reached only via `.field`, never `C.name`), so it is kept
    --     out of `members` and its default is injected at the top of `C.new`.
    ---@type table<string, boolean>
    local members = {}
    ---@type table<string, boolean>
    local instance_methods = {}
    ---@type { name: string, value: Expr | nil }[]
    local properties = {}
    for _, stmt_node in ipairs(self.ast.body) do
        if stmt_node.type == "FunctionDecl" then
            members[stmt_node.name] = true
            if not stmt_node.is_static then instance_methods[stmt_node.name] = true end
        elseif stmt_node.type == "VariableDecl" then
            if stmt_node.visibility and not stmt_node.is_static then
                properties[#properties + 1] = { name = stmt_node.name, value = stmt_node.value }
            else
                members[stmt_node.name] = true
            end
        end
    end
    Context.reset(class_name, members, instance_methods, properties)

    -- Instance-property declarations emit nothing here; their defaults are written
    -- into `C.new` (see `emit_member` for `ConstructorDecl`).
    local member_lines = {}
    for _, stmt_node in ipairs(self.ast.body) do
        if
            not (
                stmt_node.type == "VariableDecl"
                and stmt_node.visibility
                and not stmt_node.is_static
            )
        then
            member_lines[#member_lines + 1] = emit_member(stmt_node)
        end
    end

    local class_block = "local " .. class_name .. " = {}"
    if #member_lines > 0 then
        class_block = class_block .. "\n\n" .. table.concat(member_lines, "\n")
    end

    local sections = {}
    if with_header then sections[#sections + 1] = HEADER end
    sections[#sections + 1] = class_block
    if with_entry then
        -- The entry of a program is its constructor: the chunk constructs the
        -- class and returns the instance, forwarding the launch arguments
        -- (`...`) into the constructor. An entry program must have a constructor.
        if not self:_has_constructor() then
            Error.throw(
                Error.Type.MISSING_CONSTRUCTOR,
                "The entry class '" .. class_name .. "' must define a constructor"
            )
        end
        sections[#sections + 1] = "return " .. class_name .. ".new(...)"
    end

    return table.concat(sections, "\n\n")
end

return Codegen
