--------------------------------------------------------------------
-- Generated by the Lazarus compiler v1.0 (self-hosted)
-- Target runtime: Lua 5.1
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local function __lz_list(...)
    return { kind = 'list', items = { ... } }
end
local function __lz_map(items)
    return { kind = 'map', items = items }
end
local function __lz_some(v)
    return { kind = 'Some', _1 = v }
end
local function __lz_none()
    return 'None'
end
local function __lz_ok(v)
    return { kind = 'Ok', _1 = v }
end
local function __lz_err(m)
    return { kind = 'Err', _1 = m }
end
local function __lz_wrap(v)
    if v == nil then return 'None' end
    return { kind = 'Some', _1 = v }
end
local function __lz_is_some(o)
    return type(o) == 'table' and o.kind == 'Some'
end
local function __lz_is_none(o)
    return o == 'None'
end
local function __lz_is_ok(o)
    return type(o) == 'table' and o.kind == 'Ok'
end
local function __lz_is_err(o)
    return type(o) == 'table' and o.kind == 'Err'
end
local function __lz_unwrap(o)
    if type(o) == 'table' and (o.kind == 'Some' or o.kind == 'Ok') then return o._1 end
    if type(o) == 'table' and o.kind == 'Err' then error(o._1) end
    error('unwrap of a None value')
end
local function __lz_unwrap_or(o, d)
    if type(o) == 'table' and (o.kind == 'Some' or o.kind == 'Ok') then return o._1 end
    return d
end
local function __lz_error(o)
    return o._1
end
local function __lz_len(c)
    if c.kind == 'list' then return #c.items end
    local n = 0
    for _ in pairs(c.items) do n = n + 1 end
    return n
end
local function __lz_push(c, v)
    c.items[#c.items + 1] = v
end
local function __lz_pop(c)
    local n = #c.items
    if n == 0 then return 'None' end
    local v = c.items[n]
    c.items[n] = nil
    return { kind = 'Some', _1 = v }
end
local function __lz_get(c, k)
    local v = c.items[k]
    if v == nil then return 'None' end
    return { kind = 'Some', _1 = v }
end
local function __lz_has(c, k)
    return c.items[k] ~= nil
end
local function __lz_idx_get(c, i)
    if c.kind == 'list' then return c.items[i + 1] end
    return c.items[i]
end
local function __lz_idx_set(c, i, v)
    if c.kind == 'list' then
        c.items[i + 1] = v
    else
        c.items[i] = v
    end
end
local function __lz_str_find(s, sub)
    return (string.find(s, sub, 1, true))
end
local function __lz_argv(i)
    if arg == nil then return nil end
    return arg[i]
end
local function __lz_readfile(path)
    local f = io.open(path, 'r')
    if f == nil then return nil end
    local data = f:read('*a')
    f:close()
    return data
end
local function __lz_each(c)
    if c.kind == 'list' then
        local i = 0
        return function()
            i = i + 1
            if i > #c.items then return nil end
            return i - 1, c.items[i]
        end
    end
    return pairs(c.items)
end

local List = {}

function List.map(xs, f)
    local result = __lz_list()
    for _, x in __lz_each(xs) do
        __lz_push(result, f(x))
    end
    return result
end
function List.filter(xs, f)
    local result = __lz_list()
    for _, x in __lz_each(xs) do
        if f(x) then
            __lz_push(result, x)
        end
    end
    return result
end
function List.fold(xs, init, f)
    local acc = init
    for _, x in __lz_each(xs) do
        acc = f(acc, x)
    end
    return acc
end
function List.any(xs, f)
    for _, x in __lz_each(xs) do
        if f(x) then
            return true
        end
    end
    return false
end
function List.all(xs, f)
    for _, x in __lz_each(xs) do
        if not f(x) then
            return false
        end
    end
    return true
end
function List.find(xs, f)
    for _, x in __lz_each(xs) do
        if f(x) then
            return __lz_some(x)
        end
    end
    return __lz_none()
end

local Map = {}

function Map.map(m, f)
    local result = __lz_map({})
    for k, v in __lz_each(m) do
        __lz_idx_set(result, k, f(k, v))
    end
    return result
end
function Map.filter(m, f)
    local result = __lz_map({})
    for k, v in __lz_each(m) do
        if f(k, v) then
            __lz_idx_set(result, k, v)
        end
    end
    return result
end
function Map.fold(m, init, f)
    local acc = init
    for k, v in __lz_each(m) do
        acc = f(acc, k, v)
    end
    return acc
end
function Map.any(m, f)
    for k, v in __lz_each(m) do
        if f(k, v) then
            return true
        end
    end
    return false
end
function Map.all(m, f)
    for k, v in __lz_each(m) do
        if not f(k, v) then
            return false
        end
    end
    return true
end
function Map.find(m, f)
    for k, v in __lz_each(m) do
        if f(k, v) then
            return __lz_some(v)
        end
    end
    return __lz_none()
end

local TestCollectionHOF = {}

function TestCollectionHOF.new()
    local self = {}
    local nums = __lz_list(1, 2, 3, 4, 5)
    local doubled = List.map(nums, function(x)
        return x * 2
    end)
    __lz_wrap(print(doubled))
    local evens = List.filter(nums, function(x)
        return ((x - math.floor(x / 2) * 2)) == 0
    end)
    __lz_wrap(print(evens))
    local total = List.fold(nums, 0, function(acc, x)
        return acc + x
    end)
    __lz_wrap(print(total))
    local has_big = List.any(nums, function(x)
        return x > 4
    end)
    __lz_wrap(print(has_big))
    local all_pos = List.all(nums, function(x)
        return x > 0
    end)
    __lz_wrap(print(all_pos))
    local found = List.find(nums, function(x)
        return x == 3
    end)
    __lz_wrap(print(__lz_unwrap(found)))
    local scores = __lz_map({["alice"] = 9, ["bob"] = 7, ["carol"] = 5})
    local big = Map.filter(scores, function(k, v)
        return v >= 7
    end)
    __lz_wrap(print(big))
    local total_score = Map.fold(scores, 0, function(acc, k, v)
        return acc + v
    end)
    __lz_wrap(print(total_score))
    return self
end

return TestCollectionHOF.new(...)