local Lexer     = require("frontend.lexer")
local Parser    = require("frontend.parser")
local Schematic = require("frontend.schematic")
local Optimizer = require("frontend.optimizer")
local Codegen   = require("backend")

local load_chunk = loadstring or load

--- Run the front end and optimizer, returning the AST ready for codegen.
local function build(source)
    local ast = Parser.new(Lexer.new(source):scan(), source):parse()
    Schematic.analyze(ast, source)
    return Optimizer.optimize(ast)
end

--- Generated Lua body only — header and footer disabled so the assertions
--- below see the bare statement output.
local function compile(source)
    return Codegen.new(build(source)):generate({ header = false, entry = false })
end

--- Full program output, including the banner header and `main()` footer.
local function compile_program(source)
    return Codegen.new(build(source)):generate()
end

describe("Codegen", function ()
    describe("emission", function ()
        it("emits a variable declaration as a local", function ()
            assert.equal("local x = 5", compile("private x = 5"))
        end)

        it("emits a valueless mutable declaration as a bare local", function ()
            assert.equal("local x", compile("private mut x"))
        end)

        it("folds and emits an immutable declaration as a local", function ()
            assert.equal("local foo = 5", compile("private foo = 3 + 2"))
        end)

        it("emits a public binding as a global (no local)", function ()
            assert.equal("x = 5", compile("public x = 5"))
        end)

        it("emits a reassignment without 'local'", function ()
            assert.equal("local function f()\n    local n = 0\n    n = 1\n    return n\nend",
                compile("fn f() { mut n = 0\nn = 1\nreturn n }"))
        end)

        it("parenthesises nested binary operands", function ()
            -- `a` is mutable, so it is not propagated/folded and must round-trip.
            assert.equal("local a = 1\nlocal b = (a + 1) * 2",
                compile("private mut a = 1\nprivate b = (a + 1) * 2"))
        end)

        it("emits string literals via %q", function ()
            assert.equal('local s = "hi"', compile('private s = "hi"'))
        end)
    end)

    describe("control flow", function ()
        it("emits if / elseif / else", function ()
            local out = compile("fn f(a, b) { if a { x = 1 } else if b { x = 2 } else { x = 3 } }")
            assert.matches("if a then", out)
            assert.matches("elseif b then", out)
            assert.matches("\n    else\n", out)
            assert.matches("\n    end", out)
        end)

        it("emits a while loop", function ()
            local out = compile("fn f(n) { mut i = 0\nwhile i < n { i = i + 1 } }")
            assert.matches("while i < n do", out)
        end)

        it("emits loop as 'while true'", function ()
            local out = compile("fn f() { loop { break } }")
            assert.matches("while true do", out)
            assert.matches("break", out)
        end)

        it("lowers a C-style for to a do / while block", function ()
            local out = compile("fn f(n) { for i = 0; i < n; i += 1 { x = i } }")
            assert.matches("do", out)
            assert.matches("local i = 0", out)
            assert.matches("while i < n do", out)
            assert.matches("i = i %+ 1", out)
        end)

        it("emits comparison operators", function ()
            assert.matches("a == b", compile("fn f(a, b) { if a == b { x = 1 } }"))
        end)

        it("emits != as ~=", function ()
            assert.matches("a ~= b", compile("fn f(a, b) { if a != b { x = 1 } }"))
        end)

        it("emits and / or", function ()
            local out = compile("fn f(a, b) { if a and b { x = 1 } }")
            assert.matches("a and b", out)
        end)

        it("emits boolean literals", function ()
            local out = compile("fn f() { mut t = true\nt = false }")
            assert.matches("local t = true", out)
            assert.matches("t = false", out)
        end)

        it("emits unary not", function ()
            assert.matches("not a", compile("fn f(a) { if not a { x = 1 } }"))
        end)

        it("parenthesises a parenthesised binary operand of not", function ()
            assert.matches("not %(a == b%)", compile("fn f(a, b) { if not (a == b) { x = 1 } }"))
        end)
    end)

    describe("header", function ()
        it("emits a banner comment at the top by default", function ()
            local out = compile_program("private x = 5")
            assert.matches("^%-%-%-+\n%-%- Generated by the Lazarus compiler", out)
            assert.matches("Target runtime: Lua 5%.0", out)
        end)

        it("places the body after the header", function ()
            local out = compile_program("private x = 5")
            assert.matches("\n\nlocal x = 5", out)
        end)

        it("omits the header when disabled", function ()
            assert.equal("local x = 5",
                Codegen.new(build("private x = 5")):generate({ header = false, entry = false }))
        end)
    end)

    describe("footer (entry call)", function ()
        it("appends main() when a main function is present", function ()
            local out = compile_program("fn main() { return 0 }")
            assert.matches("\n\nmain%(%)$", out)
        end)

        it("does not append main() when there is no main", function ()
            local out = compile_program("fn other() { return 0 }")
            assert.is_nil(out:match("main%(%)"))
        end)

        it("omits the footer when disabled", function ()
            local out = Codegen.new(build("fn main() { return 0 }"))
                :generate({ header = true, entry = false })
            assert.is_nil(out:match("\nmain%(%)"))
        end)
    end)

    describe("output is valid Lua", function ()
        local cases = {
            "private x = 5",
            "private mut x",
            "public x = 5",
            "private foo = 3 + 2\nprivate bar = foo + 1",
            "private a = 1\nprivate b = (a + 1) * 2",
            'private s = "hello"',
            "fn counter() { mut n = 0\nn = n + 1\nreturn n }",
            "fn main() { return 0 }",
        }

        for _, src in ipairs(cases) do
            it("loads (full program): " .. src:gsub("\n", " / "), function ()
                local out = compile_program(src)
                local chunk, err = load_chunk(out)
                assert.is_truthy(chunk, "generated code failed to load: " .. tostring(err) .. "\n" .. out)
            end)
        end
    end)
end)
