local Error = require("error")

describe("Error", function()
    describe("Error.new", function()
        it("stores type, message, line, col", function()
            local e = Error.new(Error.Type.UNEXPECTED_CHAR, "bad char", 3, 7)
            assert.equal(Error.Type.UNEXPECTED_CHAR, e.type)
            assert.equal("bad char", e.message)
            assert.equal(3, e.line)
            assert.equal(7, e.col)
        end)

        it("formats with location when line and col are present", function()
            local e = Error.new(Error.Type.UNEXPECTED_CHAR, "bad char", 2, 5)
            assert.matches("%(2:5%)", tostring(e))
            assert.matches("UNEXPECTED_CHAR", tostring(e))
            assert.matches("bad char", tostring(e))
        end)

        it("formats without location when line/col are nil", function()
            local e = Error.new(Error.Type.INVALID_NUMBER, "not a number")
            local s = tostring(e)
            assert.matches("INVALID_NUMBER", s)
            assert.matches("not a number",   s)
            assert.not_matches("nil", s)
        end)
    end)

    describe("Error.throw", function()
        it("raises a Lua error", function()
            assert.has_error(function()
                Error.throw(Error.Type.UNEXPECTED_CHAR, "!")
            end)
        end)

        it("error message contains the error type", function()
            local ok, msg = pcall(function()
                Error.throw(Error.Type.UNTERMINATED_STRING, "missing quote", 1, 4)
            end)
            assert.is_false(ok)
            assert.matches("UNTERMINATED_STRING", msg)
            assert.matches("missing quote",       msg)
        end)
    end)

    describe("Error.format", function()
        it("returns the same string as tostring", function()
            local e = Error.new(Error.Type.INVALID_NUMBER, "nan", 1, 1)
            assert.equal(tostring(e), Error.format(e))
        end)
    end)

    describe("Error.Type constants", function()
        it("defines UNEXPECTED_CHAR", function()
            assert.equal("UNEXPECTED_CHAR", Error.Type.UNEXPECTED_CHAR)
        end)

        it("defines UNTERMINATED_STRING", function()
            assert.equal("UNTERMINATED_STRING", Error.Type.UNTERMINATED_STRING)
        end)

        it("defines INVALID_NUMBER", function()
            assert.equal("INVALID_NUMBER", Error.Type.INVALID_NUMBER)
        end)
    end)
end)
