local Lexer = require("frontend.lexer")
local Token = require("frontend.lexer.token")
local Error = require("error")

local function scan(source)
    return Lexer.new(source):scan()
end

local function tok(tokens, i)
    return tokens[i]
end

describe("Lexer", function ()
    describe("Token structure", function ()
        it("returns a table with type, value, line, column", function ()
            local t = Token.new("PRIVATE", "private", 1, 1)
            assert.equal("PRIVATE", t.type)
            assert.equal("private", t.value)
            assert.equal(1, t.line)
            assert.equal(1, t.column)
        end)

        it("__tostring formats correctly", function ()
            local t = Token.new("NUMBER", "42", 3, 7, 42)
            assert.equal("Token(NUMBER, 42, 3:7)", tostring(t))
        end)
    end)

    describe("empty / whitespace input", function ()
        it("returns no tokens for empty string", function ()
            assert.same({}, scan(""))
        end)

        it("returns no tokens for whitespace-only input", function ()
            assert.same({}, scan("   \t\n  "))
        end)
    end)

    describe("keywords", function ()
        it("tokenises 'private' as PRIVATE", function ()
            local tokens = scan("private")
            assert.equal(1, #tokens)
            assert.equal("PRIVATE", tok(tokens, 1).type)
            assert.equal("private", tok(tokens, 1).value)
        end)

        it("keyword tokens have nil literal", function ()
            local tokens = scan("private")
            assert.is_nil(tok(tokens, 1).literal)
        end)
    end)

    describe("identifiers", function ()
        it("tokenises a plain name as IDENTIFIER", function ()
            local tokens = scan("foo")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
            assert.equal("foo", tok(tokens, 1).value)
        end)

        it("stores identifier name in literal", function ()
            local tokens = scan("foo")
            assert.equal("foo", tok(tokens, 1).literal)
        end)

        it("tokenises underscore-prefixed names", function ()
            local tokens = scan("_bar")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
        end)

        it("tokenises names with digits after the first char", function ()
            local tokens = scan("x1y2")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
            assert.equal("x1y2", tok(tokens, 1).value)
        end)

        it("throws INVALID_NUMBER when a letter immediately follows a number literal", function ()
            local ok, err = pcall(function () scan("1foo") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.INVALID_NUMBER, err.type)
        end)
    end)

    describe("numbers", function ()
        it("tokenises a single digit", function ()
            local tokens = scan("7")
            assert.equal(1, #tokens)
            assert.equal("NUMBER", tok(tokens, 1).type)
            assert.equal(7, tok(tokens, 1).literal)
        end)

        it("tokenises a multi-digit integer", function ()
            local tokens = scan("1234")
            assert.equal(1, #tokens)
            assert.equal(1234, tok(tokens, 1).literal)
        end)

        it("stores the raw string in value and the number in literal", function ()
            local tokens = scan("99")
            assert.equal("99", tok(tokens, 1).value)
            assert.equal(99, tok(tokens, 1).literal)
        end)

        it("throws INVALID_NUMBER when a letter immediately follows a number", function ()
            local ok, err = pcall(function () scan("123abc") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.INVALID_NUMBER, err.type)
            assert.matches("after number literal", err.message)
        end)
    end)

    describe("string literals", function ()
        it("tokenises a simple string as STRING", function ()
            local tokens = scan('"hello"')
            assert.equal(1, #tokens)
            assert.equal("STRING", tok(tokens, 1).type)
        end)

        it("stores the content without quotes in literal", function ()
            local tokens = scan('"hello"')
            assert.equal("hello", tok(tokens, 1).literal)
        end)

        it("stores the raw source text with quotes in value", function ()
            local tokens = scan('"hello"')
            assert.equal('"hello"', tok(tokens, 1).value)
        end)

        it("handles an empty string", function ()
            local tokens = scan('""')
            assert.equal(1, #tokens)
            assert.equal("STRING", tok(tokens, 1).type)
            assert.equal("", tok(tokens, 1).literal)
        end)

        it("records the correct start position", function ()
            local tokens = scan('"hi"')
            assert.equal(1, tok(tokens, 1).line)
            assert.equal(1, tok(tokens, 1).column)
        end)

        it("throws UNTERMINATED_STRING for an unclosed string", function ()
            local ok, err = pcall(function () scan('"hello') end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.UNTERMINATED_STRING, err.type)
        end)

        it("throws UNTERMINATED_STRING when a newline appears inside the string", function ()
            local ok, err = pcall(function () scan('"hello\nworld"') end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.UNTERMINATED_STRING, err.type)
        end)

        it("reports the opening-quote column in UNTERMINATED_STRING", function ()
            local ok, err = pcall(function () scan('   "oops') end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(4, err.col)
        end)
    end)

    describe("symbols", function ()
        it("tokenises '=' as ASSIGN", function ()
            local tokens = scan("=")
            assert.equal(1, #tokens)
            assert.equal("ASSIGN", tok(tokens, 1).type)
        end)

        it("tokenises '+' as PLUS", function ()
            local tokens = scan("+")
            assert.equal("PLUS", tok(tokens, 1).type)
        end)

        it("tokenises '-' as MINUS", function ()
            local tokens = scan("-")
            assert.equal("MINUS", tok(tokens, 1).type)
        end)

        it("throws UNEXPECTED_CHAR with the correct error type for an unknown symbol", function ()
            local ok, err = pcall(function () scan("@") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.UNEXPECTED_CHAR, err.type)
        end)

        it("reports column 1 for an unknown symbol at the start of input", function ()
            local ok, err = pcall(function () scan("@") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(1, err.col)
        end)

        it("includes the bad character in the error message", function ()
            local ok, err = pcall(function () scan("@") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.matches("@", err.message)
        end)

        it("reports the correct column when the bad character is not at position 1", function ()
            local ok, err = pcall(function () scan("abc @") end)
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.UNEXPECTED_CHAR, err.type)
            assert.equal(5, err.col)
        end)
    end)

    describe("source positions", function ()
        it("reports line 1 col 1 for the first token", function ()
            local tokens = scan("private")
            assert.equal(1, tok(tokens, 1).line)
            assert.equal(1, tok(tokens, 1).column)
        end)

        it("advances column across a single line", function ()
            local tokens = scan("a b")
            assert.equal(1, tok(tokens, 1).column)
            assert.equal(3, tok(tokens, 2).column)
        end)

        it("advances line number after a newline", function ()
            local tokens = scan("a\nb")
            assert.equal(1, tok(tokens, 1).line)
            assert.equal(2, tok(tokens, 2).line)
        end)

        it("resets column to 1 after a newline", function ()
            local tokens = scan("a\nb")
            assert.equal(1, tok(tokens, 2).column)
        end)
    end)

    describe("compound expressions", function ()
        it("tokenises 'private x = 10 + 5' into 6 tokens", function ()
            local tokens = scan("private x = 10 + 5")
            assert.equal(6, #tokens)
            assert.equal("PRIVATE",    tok(tokens, 1).type)
            assert.equal("IDENTIFIER", tok(tokens, 2).type)
            assert.equal("ASSIGN",     tok(tokens, 3).type)
            assert.equal("NUMBER",     tok(tokens, 4).type)
            assert.equal("PLUS",       tok(tokens, 5).type)
            assert.equal("NUMBER",     tok(tokens, 6).type)
        end)

        it("tokenises 'private result = 100' into 4 tokens", function ()
            local tokens = scan("private result = 100")
            assert.equal(4, #tokens)
        end)

        it("tokenises 'x = 10' into 3 tokens", function ()
            local tokens = scan("x = 10")
            assert.equal(3, #tokens)
        end)

        it("handles leading and trailing whitespace", function ()
            local tokens = scan("  private x  ")
            assert.equal(2, #tokens)
        end)

        it("handles multiple newlines between tokens", function ()
            local tokens = scan("private\n\nx")
            assert.equal(2, #tokens)
            assert.equal(3, tok(tokens, 2).line)
        end)
    end)
end)
