local Lexer = require("frontend.lexer")
local Token = require("frontend.lexer.token")

local function scan(source)
    return Lexer.new(source):scan()
end

local function tok(tokens, i)
    return tokens[i]
end

describe("Lexer", function ()
    describe("Token structure", function ()
        it("returns a table with type, value, line, column, literal", function ()
            local t = Token.new("LET", "let", 1, 1, "let")
            assert.equal("LET", t.type)
            assert.equal("let", t.value)
            assert.equal(1, t.line)
            assert.equal(1, t.column)
            assert.equal("let", t.literal)
        end)

        it("__tostring formats correctly", function ()
            local t = Token.new("NUMBER", "42", 3, 7, 42)
            assert.equal("Token(NUMBER, 42, 3:7)", tostring(t))
        end)
    end)

    describe("empty / whitespace input", function ()
        it("returns no tokens for empty string", function ()
            assert.same({}, scan(""))
        end)

        it("returns no tokens for whitespace-only input", function ()
            assert.same({}, scan("   \t\n  "))
        end)
    end)

    describe("keywords", function ()
        it("tokenises 'let' as LET", function ()
            local tokens = scan("let")
            assert.equal(1, #tokens)
            assert.equal("LET", tok(tokens, 1).type)
            assert.equal("let", tok(tokens, 1).value)
        end)
    end)

    describe("identifiers", function ()
        it("tokenises a plain name as IDENTIFIER", function ()
            local tokens = scan("foo")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
            assert.equal("foo", tok(tokens, 1).value)
        end)

        it("tokenises underscore-prefixed names", function ()
            local tokens = scan("_bar")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
        end)

        it("tokenises names with digits after the first char", function ()
            local tokens = scan("x1y2")
            assert.equal(1, #tokens)
            assert.equal("IDENTIFIER", tok(tokens, 1).type)
            assert.equal("x1y2", tok(tokens, 1).value)
        end)

        it("does NOT tokenise a digit-leading name as a single identifier", function ()
            -- '1foo' → NUMBER(1) + IDENTIFIER(foo)
            local tokens = scan("1foo")
            assert.equal(2, #tokens)
            assert.equal("NUMBER", tok(tokens, 1).type)
            assert.equal("IDENTIFIER", tok(tokens, 2).type)
        end)
    end)

    describe("numbers", function ()
        it("tokenises a single digit", function ()
            local tokens = scan("7")
            assert.equal(1, #tokens)
            assert.equal("NUMBER", tok(tokens, 1).type)
            assert.equal(7, tok(tokens, 1).literal)
        end)

        it("tokenises a multi-digit integer", function ()
            local tokens = scan("1234")
            assert.equal(1, #tokens)
            assert.equal(1234, tok(tokens, 1).literal)
        end)

        it("stores the raw string in value and the number in literal", function ()
            local tokens = scan("99")
            assert.equal("99", tok(tokens, 1).value)
            assert.equal(99, tok(tokens, 1).literal)
        end)
    end)

    describe("symbols", function ()
        it("tokenises '=' as ASSIGN", function ()
            local tokens = scan("=")
            assert.equal(1, #tokens)
            assert.equal("ASSIGN", tok(tokens, 1).type)
        end)

        it("tokenises '+' as PLUS", function ()
            local tokens = scan("+")
            assert.equal("PLUS", tok(tokens, 1).type)
        end)

        it("tokenises '-' as MINUS", function ()
            local tokens = scan("-")
            assert.equal("MINUS", tok(tokens, 1).type)
        end)

        it("throws on an unknown symbol", function ()
            assert.has_error(function ()
                scan("@")
            end)
        end)
    end)

    describe("source positions", function ()
        it("reports line 1 col 1 for the first token", function ()
            local tokens = scan("let")
            assert.equal(1, tok(tokens, 1).line)
            assert.equal(1, tok(tokens, 1).column)
        end)

        it("advances column across a single line", function ()
            local tokens = scan("a b")
            assert.equal(1, tok(tokens, 1).column)
            assert.equal(3, tok(tokens, 2).column)
        end)

        it("advances line number after a newline", function ()
            local tokens = scan("a\nb")
            assert.equal(1, tok(tokens, 1).line)
            assert.equal(2, tok(tokens, 2).line)
        end)

        it("resets column to 1 after a newline", function ()
            local tokens = scan("a\nb")
            assert.equal(1, tok(tokens, 2).column)
        end)
    end)

    describe("compound expressions", function ()
        it("tokenises 'let x = 10 + 5' into 6 tokens", function ()
            local tokens = scan("let x = 10 + 5")
            assert.equal(6, #tokens)
            assert.equal("LET", tok(tokens, 1).type)
            assert.equal("IDENTIFIER", tok(tokens, 2).type)
            assert.equal("ASSIGN", tok(tokens, 3).type)
            assert.equal("NUMBER", tok(tokens, 4).type)
            assert.equal("PLUS", tok(tokens, 5).type)
            assert.equal("NUMBER", tok(tokens, 6).type)
        end)

        it("tokenises 'let result = 100' into 4 tokens", function ()
            local tokens = scan("let result = 100")
            assert.equal(4, #tokens)
        end)

        it("tokenises 'x = 10' into 3 tokens", function ()
            local tokens = scan("x = 10")
            assert.equal(3, #tokens)
        end)

        it("handles leading and trailing whitespace", function ()
            local tokens = scan("  let x  ")
            assert.equal(2, #tokens)
        end)

        it("handles multiple newlines between tokens", function ()
            local tokens = scan("let\n\nx")
            assert.equal(2, #tokens)
            assert.equal(3, tok(tokens, 2).line)
        end)
    end)
end)
