local Lexer     = require("frontend.lexer")
local Parser    = require("frontend.parser")
local Schematic = require("frontend.schematic")
local Error     = require("error")

local function analyze(source)
    local ast = Parser.new(Lexer.new(source):scan(), source):parse()
    Schematic.analyze(ast, source)
    return ast
end

describe("Schematic", function ()
    describe("valid programs", function ()
        it("accepts a declaration and a later reference to it", function ()
            assert.has_no.errors(function ()
                analyze("private x = 1\nprivate y = x")
            end)
        end)

        it("accepts an immutable binding referenced in a later expression", function ()
            assert.has_no.errors(function ()
                analyze("private foo = 3\nprivate bar = foo + 1")
            end)
        end)

        it("accepts reassignment of a mutable binding inside a function", function ()
            assert.has_no.errors(function ()
                analyze("fn f() { mut n = 0\nn = 1\nreturn n }")
            end)
        end)
    end)

    describe("mutability", function ()
        it("rejects reassignment of an immutable binding", function ()
            local ok, err = pcall(analyze, "fn f() { a = 1\na = 2\nreturn a }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("Cannot assign to immutable binding 'a'", err.message)
        end)

        it("rejects reassignment of a function parameter", function ()
            local ok, err = pcall(analyze, "fn f(a) { a = 2\nreturn a }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.matches("Cannot assign to immutable binding 'a'", err.message)
        end)
    end)

    describe("visibility", function ()
        it("rejects a top-level binding with no visibility modifier", function ()
            local ok, err = pcall(analyze, "x = 1")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("must declare visibility", err.message)
        end)

        it("accepts a bare binding inside a function", function ()
            assert.has_no.errors(function ()
                analyze("fn f() { a = 1\nreturn a }")
            end)
        end)
    end)

    describe("duplicate declarations", function ()
        it("rejects a redeclared name with SEMANTIC_ERROR and a position", function ()
            local ok, err = pcall(analyze, "private x = 1\nprivate x = 2")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("Duplicate declaration 'x'", err.message)
            assert.equal(2, err.line)
            assert.is_number(err.col)
        end)
    end)

    describe("undeclared identifiers", function ()
        it("rejects a reference to an unknown name with a source position", function ()
            local ok, err = pcall(analyze, "private y = nope")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("Undeclared identifier 'nope'", err.message)
            assert.equal(1, err.line)
            assert.equal(13, err.col)
        end)

        it("rejects self-reference in an initialiser", function ()
            local ok, err = pcall(analyze, "private x = x")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
        end)
    end)

    describe("control flow", function ()
        it("accepts if / else if / else referencing visible names", function ()
            assert.has_no.errors(function ()
                analyze("fn f(a, b) { if a { x = 1 } else if b { x = 2 } else { x = 3 } }")
            end)
        end)

        it("accepts a while loop mutating an outer mutable binding", function ()
            assert.has_no.errors(function ()
                analyze("fn f(n) { mut i = 0\n while i < n { i = i + 1 } }")
            end)
        end)

        it("accepts an infinite loop containing break", function ()
            assert.has_no.errors(function ()
                analyze("fn f() { loop { break } }")
            end)
        end)

        it("accepts a C-style for whose step mutates the loop variable", function ()
            -- the loop variable `i` is a fresh, implicitly-mutable binding, so the
            -- `i += 1` step must be legal even though it was not declared `mut`.
            assert.has_no.errors(function ()
                analyze("fn f(n) { for i = 0; i < n; i += 1 { x = i } }")
            end)
        end)

        it("rejects an undeclared identifier in a condition", function ()
            local ok, err = pcall(analyze, "fn f() { while nope { x = 1 } }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("Undeclared identifier 'nope'", err.message)
        end)

        it("does not leak a binding declared inside an if body", function ()
            local ok, err = pcall(analyze, "fn f(a) { if a { y = 1 }\n return y }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.matches("Undeclared identifier 'y'", err.message)
        end)

        it("rejects break outside any loop", function ()
            local ok, err = pcall(analyze, "fn f() { break }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("'break' outside", err.message)
        end)

        it("rejects break that is not the last statement in its block", function ()
            local ok, err = pcall(analyze, "fn f() { loop { break\n x = 1 } }")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.matches("'break' must be the last statement", err.message)
        end)

        it("checks operands of a unary expression", function ()
            local ok, err = pcall(analyze, "private x = not nope")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.matches("Undeclared identifier 'nope'", err.message)
        end)

        it("accepts a unary expression over a visible name", function ()
            assert.has_no.errors(function ()
                analyze("private p = true\nprivate q = not p")
            end)
        end)
    end)

    describe("bare expression statements", function ()
        it("rejects a bare expression as a statement", function ()
            local ok, err = pcall(analyze, "private x = 1\nx + x")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("Bare expressions are not valid statements", err.message)
        end)
    end)

    describe("type checking", function ()
        local function bad(source)
            local ok, err = pcall(analyze, source)
            assert.is_false(ok, "expected a type error for: " .. source)
            return err --[[@as Error]]
        end

        describe("gradual (un-annotated code still type-checks)", function ()
            it("accepts un-annotated functions and bindings", function ()
                assert.has_no.errors(function ()
                    analyze("fn double(n) { return n * 2 }\nprivate x = double(3)")
                end)
            end)
        end)

        describe("annotation vs initialiser", function ()
            it("accepts a matching annotation", function ()
                assert.has_no.errors(function () analyze("private x: int = 5") end)
            end)

            it("rejects an int annotation initialised with a float", function ()
                local err = bad("private x: int = 3.5")
                assert.equal(Error.Type.TYPE_MISMATCH, err.type)
                assert.matches("Binding 'x'", err.message)
            end)

            it("rejects a str annotation initialised with a number", function ()
                assert.equal(Error.Type.TYPE_MISMATCH, bad("private s: str = 1").type)
            end)
        end)

        describe("int / float strictness", function ()
            it("accepts int + int", function ()
                assert.has_no.errors(function () analyze("private a: int = 1\nprivate b = a + 2") end)
            end)

            it("rejects mixing int and float in arithmetic", function ()
                local err = bad("private a: int = 1\nprivate b: float = 2.0\nprivate c = a + b")
                assert.equal(Error.Type.TYPE_MISMATCH, err.type)
                assert.matches("int and float do not convert", err.message)
            end)
        end)

        describe("operator operand types", function ()
            it("rejects arithmetic on a string", function ()
                assert.equal(Error.Type.TYPE_MISMATCH, bad('private s: str = "x"\nprivate n = s * 2').type)
            end)

            it("rejects ++ on numbers", function ()
                assert.equal(Error.Type.TYPE_MISMATCH, bad("private a: int = 1\nprivate b = a ++ a").type)
            end)

            it("accepts ++ on strings", function ()
                assert.has_no.errors(function ()
                    analyze('private a: str = "x"\nprivate b = a ++ a')
                end)
            end)

            it("rejects 'and' on non-bool operands", function ()
                assert.equal(Error.Type.TYPE_MISMATCH, bad("private a: int = 1\nprivate b = a and a").type)
            end)
        end)

        describe("conditions must be bool", function ()
            it("accepts a bool condition", function ()
                assert.has_no.errors(function ()
                    analyze("private flag: bool = true\nif flag { private mut x = 1 }")
                end)
            end)

            it("rejects a non-bool if condition", function ()
                local err = bad("private n: int = 5\nif n { private mut x = 1 }")
                assert.equal(Error.Type.TYPE_MISMATCH, err.type)
                assert.matches("must be 'bool'", err.message)
            end)

            it("rejects a non-bool while condition", function ()
                assert.equal(Error.Type.TYPE_MISMATCH,
                    bad("private n: int = 5\nwhile n { private mut x = 1 }").type)
            end)
        end)

        describe("return type", function ()
            it("accepts a return matching the declared type", function ()
                assert.has_no.errors(function ()
                    analyze("fn two(): int { return 2 }")
                end)
            end)

            it("rejects a return that violates the declared type", function ()
                local err = bad('fn two(): int { return "two" }')
                assert.equal(Error.Type.TYPE_MISMATCH, err.type)
                assert.matches("Function return", err.message)
            end)

            it("checks a typed parameter flows into the return check", function ()
                assert.has_no.errors(function ()
                    analyze("fn id(n: int): int { return n }")
                end)
            end)
        end)

        describe("typed mutable reassignment", function ()
            it("rejects assigning the wrong type to a typed mutable", function ()
                local err = bad('public mut count: int = 0\nfn f() { count = "no" }')
                assert.equal(Error.Type.TYPE_MISMATCH, err.type)
            end)
        end)
    end)

    describe("constructor", function ()
        it("accepts a constructor whose body uses self and params", function ()
            assert.has_no.errors(function ()
                analyze("constructor(x, y) { self.x = x\nself.y = y }")
            end)
        end)

        it("accepts construction of the class by name", function ()
            assert.has_no.errors(function ()
                analyze("constructor(x) { self.x = x }\nfn main() { mut p = Main(5)\nreturn p.x }")
            end)
        end)

        it("rejects a constructor nested inside a function", function ()
            local ok, err = pcall(analyze, "fn f() { constructor() {} }")
            assert.is_false(ok)
            assert.matches("must be at the top level", (err --[[@as Error]]).message)
        end)

        it("rejects a value return inside a constructor", function ()
            local ok, err = pcall(analyze, "constructor() { return 1 }")
            assert.is_false(ok)
            assert.matches("'return' outside of a function", (err --[[@as Error]]).message)
        end)
    end)

    describe("field access", function ()
        it("accepts field read and assignment on a declared object", function ()
            assert.has_no.errors(function ()
                analyze("fn f(p) { p.x = 1\nreturn p.x }")
            end)
        end)

        it("rejects field assignment on an undeclared object", function ()
            local ok, err = pcall(analyze, "fn f() { nope.x = 1 }")
            assert.is_false(ok)
            assert.matches("Undeclared identifier 'nope'", (err --[[@as Error]]).message)
        end)
    end)

    describe("casing", function ()
        it("accepts snake_case values and scalar / PascalCase types", function ()
            assert.has_no.errors(function ()
                analyze("private my_var: int = 1\nfn do_thing(a_b: int): int { return a_b }")
            end)
        end)

        it("rejects a non-snake_case binding name", function ()
            local ok, err = pcall(analyze, "private myVar = 1")
            assert.is_false(ok)
            local err = err --[[@as Error]]
            assert.equal(Error.Type.SEMANTIC_ERROR, err.type)
            assert.matches("must be snake_case", err.message)
        end)

        it("rejects a non-snake_case function name", function ()
            local ok, err = pcall(analyze, "fn DoThing() { return 1 }")
            assert.is_false(ok)
            assert.matches("must be snake_case", (err --[[@as Error]]).message)
        end)

        it("rejects a non-snake_case parameter name", function ()
            local ok, err = pcall(analyze, "fn f(myArg) { return myArg }")
            assert.is_false(ok)
            assert.matches("must be snake_case", (err --[[@as Error]]).message)
        end)

        it("rejects a non-snake_case loop variable", function ()
            local ok, err = pcall(analyze, "fn f() { for Idx = 0; Idx < 3; Idx += 1 { x = Idx } }")
            assert.is_false(ok)
            assert.matches("must be snake_case", (err --[[@as Error]]).message)
        end)

        it("rejects a lower-case (non-scalar) type name", function ()
            local ok, err = pcall(analyze, "private x: foo = 1")
            assert.is_false(ok)
            assert.matches("must be PascalCase", (err --[[@as Error]]).message)
        end)

        it("accepts a PascalCase type name (treated as any for now)", function ()
            assert.has_no.errors(function () analyze("private mut x: Widget") end)
        end)
    end)
end)
