local TokenBuilder = require("frontend.lexer.token_builder")

describe("TokenBuilder", function ()
    describe("make", function ()
        it("creates a pending token with zero position", function ()
            local p = TokenBuilder.make("PRIVATE", "private")
            assert.equal("PRIVATE", p.type)
            assert.equal("private", p.value)
            assert.equal("private", p.literal)
            assert.equal(0, p.line)
            assert.equal(0, p.column)
        end)
    end)

    describe("with_position", function ()
        it("promotes a pending token to a Token with the given position", function ()
            local p = TokenBuilder.make("ASSIGN", "=")
            local t = TokenBuilder.with_position(p, 4, 12)
            assert.equal("ASSIGN", t.type)
            assert.equal("=", t.value)
            assert.equal(4, t.line)
            assert.equal(12, t.column)
        end)
    end)

    describe("number", function ()
        it("creates a NUMBER token with numeric literal", function ()
            local t = TokenBuilder.number("42", 1, 5)
            assert.equal("NUMBER", t.type)
            assert.equal("42", t.value)
            assert.equal(42, t.literal)
            assert.equal(1, t.line)
            assert.equal(5, t.column)
        end)

        it("converts the string to a number via tonumber", function ()
            local t = TokenBuilder.number("007", 1, 1)
            assert.equal(7, t.literal)
        end)
    end)

    describe("identifier", function ()
        it("creates a token with the given type and value as literal", function ()
            local t = TokenBuilder.identifier("IDENTIFIER", "myVar", 2, 3)
            assert.equal("IDENTIFIER", t.type)
            assert.equal("myVar", t.value)
            assert.equal("myVar", t.literal)
            assert.equal(2, t.line)
            assert.equal(3, t.column)
        end)

        it("works for keyword types too", function ()
            local t = TokenBuilder.identifier("PRIVATE", "private", 1, 1)
            assert.equal("PRIVATE", t.type)
        end)
    end)
end)
