--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v1.0)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local base = 7
local scaled = 20
total = 27