--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Arithmetic = {}

Arithmetic.base = 7
Arithmetic.scaled = 20
Arithmetic.total = 27

return Arithmetic