--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Arithmetic = {}

Arithmetic.base = 7
Arithmetic.scaled = 20
function Arithmetic.new()
    local self = {}
    self.total = 27
    return self
end

return Arithmetic.new(...)