--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Functions = {}

Functions.offset = 10
function Functions.double(n)
    return n * 2
end
function Functions.shift(n)
    return n + 10
end
function Functions.main()
    return Functions.shift(Functions.double(5))
end

Functions.main()
return Functions