--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v1.0)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local offset = 10
local function double(n)
    return n * 2
end
local function shift(n)
    return n + 10
end
local function main()
    return shift(double(5))
end

main()