--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v1.0)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

counter = 0
local function step(v)
    local total = v
    total = total + 1
    total = total * 2
    return total
end
local function main()
    counter = step(4)
    return counter
end

main()