--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Mutability = {}

Mutability.counter = 0
function Mutability.step(v)
    local total = v
    total = total + 1
    total = total * 2
    return total
end
function Mutability.main()
    Mutability.counter = Mutability.step(4)
    return Mutability.counter
end

Mutability.main()
return Mutability