--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Mutability = {}

function Mutability.step(v)
    local total = v
    total = total + 1
    total = total * 2
    return total
end
function Mutability.new()
    local self = {}
    self.counter = Mutability.step(4)
    return self
end

return Mutability.new(...)