--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v1.0)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local base = 7
local scale = 20
answer = 0
label = "none"
local function square(n)
    return n * n
end
local function step(v)
    local r = v
    r = r * 2
    r = r + 7
    return r
end
local function compute(seed)
    local function bump(x)
        return x + 7
    end
    local total = seed
    total = total + square(seed)
    total = step(total)
    total = bump(total)
    total = total + 20
    return total
end
local function brand()
    return "lazarus"
end
local function main()
    answer = compute(4)
    label = brand()
    return answer
end

main()