--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Showcase = {}

Showcase.base = 7
Showcase.scale = 20
function Showcase.square(n)
    return n * n
end
function Showcase.step(v)
    local r = v
    r = r * 2
    r = r + 7
    return r
end
function Showcase.compute(seed)
    local function bump(x)
        return x + 7
    end
    local total = seed
    total = total + Showcase.square(seed)
    total = Showcase.step(total)
    total = bump(total)
    total = total + 20
    return total
end
function Showcase.brand()
    return "lazarus"
end
function Showcase.describe(self)
    return (self.label .. " = ") .. "ready"
end
function Showcase.new()
    local self = {}
    self.answer = Showcase.compute(4)
    self.label = Showcase.brand()
    self.summary = Showcase.describe(self)
    return self
end

return Showcase.new(...)