--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Showcase = {}

Showcase.base = 7
Showcase.scale = 20
Showcase.answer = 0
Showcase.label = "none"
function Showcase.square(n)
    return n * n
end
function Showcase.step(v)
    local r = v
    r = r * 2
    r = r + 7
    return r
end
function Showcase.compute(seed)
    local function bump(x)
        return x + 7
    end
    local total = seed
    total = total + Showcase.square(seed)
    total = Showcase.step(total)
    total = bump(total)
    total = total + 20
    return total
end
function Showcase.brand()
    return "lazarus"
end
function Showcase.main()
    Showcase.answer = Showcase.compute(4)
    Showcase.label = Showcase.brand()
    return Showcase.answer
end

Showcase.main()
return Showcase