--------------------------------------------------------------------
-- Generated by the Lazarus compiler (v0.1)
-- Target runtime: Lua 5.0
-- This file is auto-generated. Do not edit by hand.
--------------------------------------------------------------------

local Test = {}

function Test.test_func(a)
    return a + 1
end
function Test.main()
    local a = 0
    local b = 2
    do
        local i = 0
        while i < 10 do
            a = a(a)
            i = i + 1
        end
    end
end

Test.main()
return Test