[book]
title = "Laze"
description = "A statically-typed language that compiles to Lua"
src = "../doc/design"
language = "en"

[build]
build-dir = "dist"

[output.html]
git-repository-url = "https://github.com/NightmarePog/Laze"
edit-url-template = "https://github.com/NightmarePog/Laze/edit/main/doc/design/{path}"
site-url = "/Laze/"
